CREATE TABLE "IDS"."CLIENT"
(
    "ID" VARCHAR(255) NOT NULL,
    "CLIENTID" VARCHAR(255) NOT NULL,
    "CLIENTIDISSUEDAT" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "CLIENTSECRET" VARCHAR(255) DEFAULT NULL,
    "CLIENTSECRETEXPIRESAT" TIMESTAMP(6) DEFAULT NULL,
    "CLIENTNAME" VARCHAR(255) NOT NULL,
    "CLIENTAUTHENTICATIONMETHODS" VARCHAR(1000) NOT NULL,
    "AUTHORIZATIONGRANTTYPES" VARCHAR(1000) NOT NULL,
    "REDIRECTURIS" VARCHAR(1000) DEFAULT NULL,
    "POSTLOGOUTREDIRECTURIS" VARCHAR(1000) DEFAULT NULL,
    "SCOPES" VARCHAR(1000) NOT NULL,
    "CLIENTSETTINGS" VARCHAR(2000) NOT NULL,
    "TOKENSETTINGS" VARCHAR(2000) NOT NULL,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;


CREATE TABLE "IDS"."AUTHORIZATIONCONSENT"
(
    "REGISTEREDCLIENTID" VARCHAR(255) NOT NULL,
    "PRINCIPALNAME" VARCHAR(255) NOT NULL,
    "AUTHORITIES" VARCHAR(1000) NOT NULL,
    NOT CLUSTER PRIMARY KEY("REGISTEREDCLIENTID", "PRINCIPALNAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;


CREATE TABLE "IDS"."AUTHORIZATION"
(
    "ID" VARCHAR(255) NOT NULL,
    "REGISTEREDCLIENTID" VARCHAR(255) NOT NULL,
    "PRINCIPALNAME" VARCHAR(255) NOT NULL,
    "AUTHORIZATIONGRANTTYPE" VARCHAR(255) NOT NULL,
    "AUTHORIZEDSCOPES" VARCHAR(1000) DEFAULT NULL,
    "ATTRIBUTES" VARCHAR(4000) DEFAULT NULL,
    "STATE" VARCHAR(500) DEFAULT NULL,
    "AUTHORIZATIONCODEVALUE" VARCHAR(4000) DEFAULT NULL,
    "AUTHORIZATIONCODEISSUEDAT" TIMESTAMP(6) DEFAULT NULL,
    "AUTHORIZATIONCODEEXPIRESAT" TIMESTAMP(6) DEFAULT NULL,
    "AUTHORIZATIONCODEMETADATA" VARCHAR(2000) DEFAULT NULL,
    "ACCESSTOKENVALUE" VARCHAR(4000) DEFAULT NULL,
    "ACCESSTOKENISSUEDAT" TIMESTAMP(6) DEFAULT NULL,
    "ACCESSTOKENEXPIRESAT" TIMESTAMP(6) DEFAULT NULL,
    "ACCESSTOKENMETADATA" VARCHAR(2000) DEFAULT NULL,
    "ACCESSTOKENTYPE" VARCHAR(255) DEFAULT NULL,
    "ACCESSTOKENSCOPES" VARCHAR(1000) DEFAULT NULL,
    "REFRESHTOKENVALUE" VARCHAR(4000) DEFAULT NULL,
    "REFRESHTOKENISSUEDAT" TIMESTAMP(6) DEFAULT NULL,
    "REFRESHTOKENEXPIRESAT" TIMESTAMP(6) DEFAULT NULL,
    "REFRESHTOKENMETADATA" VARCHAR(2000) DEFAULT NULL,
    "OIDCIDTOKENVALUE" VARCHAR(4000) DEFAULT NULL,
    "OIDCIDTOKENISSUEDAT" TIMESTAMP(6) DEFAULT NULL,
    "OIDCIDTOKENEXPIRESAT" TIMESTAMP(6) DEFAULT NULL,
    "OIDCIDTOKENMETADATA" VARCHAR(2000) DEFAULT NULL,
    "OIDCIDTOKENCLAIMS" VARCHAR(2000) DEFAULT NULL,
    "USERCODEVALUE" VARCHAR(4000) DEFAULT NULL,
    "USERCODEISSUEDAT" TIMESTAMP(6) DEFAULT NULL,
    "USERCODEEXPIRESAT" TIMESTAMP(6) DEFAULT NULL,
    "USERCODEMETADATA" VARCHAR(2000) DEFAULT NULL,
    "DEVICECODEVALUE" VARCHAR(4000) DEFAULT NULL,
    "DEVICECODEISSUEDAT" TIMESTAMP(6) DEFAULT NULL,
    "DEVICECODEEXPIRESAT" TIMESTAMP(6) DEFAULT NULL,
    "DEVICECODEMETADATA" VARCHAR(2000) DEFAULT NULL,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

