debug: false


spring:
  datasource:
    url: jdbc:dm://localhost:15236:IDS
    username: IDS
    password: SYSDBA
    driver-class-name: dm.jdbc.driver.DmDriver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.DmDialect
