server:
  port: 9000

spring:
  datasource:
    url: jdbc:dm://47.103.131.111:15236:IDS
    username: IDS
    password: withub!@#
    driver-class-name: dm.jdbc.driver.DmDriver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.DmDialect